Feature/basic structure #PR
fabianomag/apple-income pull request #1
Opened 2022-02-16 19:00 UTC by fabianofrank

Add basic structure with style and updated readme file

2022-02-16 19:30 UTC, Lameck1 requested changes
Hi, @fabianofrank, 

Good job so far 👏🏿!

### Some highlights
* Correct gitflow practice ✔️ 
* Good commit messages ✔️ 
* Professional README ✔️ 
* In the project:
   * Good usage of the react-router-dom package ✔️ 
   * Clean codebase ✔️ 
   * Redux store and redux logic properly implemented ✔️  
   * All expected features of the MVP functioning as expected ✔️

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-16 19:30 UTC, Lameck1 commented on README.md
> +
- [ ] As part of the project requirements, pease add an "Acknowledgements" section or similar that gives appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2022-02-16 19:30 UTC, Lameck1 commented on README.md
> +[GitHub Link](https://fabianofrank.github.io/apple-income/)
- [ ] In this section of the README, we should have the following:
  - A link to the project's video presentation
  - A link to the deployed live version of the project
  Please add these to the README.
  
  ### Answer to the question you left in the Code Review Request
  I would recommend you use Netlify for deployment. It is a simpler process and this React would be very responsive on Netlify. Here is a [GUIDE](https://medium.com/geekculture/how-to-deploy-react-projects-on-netlify-28f72b4ceb8c) to help with the deployment to Netlify.

2022-02-17 20:21 UTC, leolpaz approved these changes
Hi @fabianofrank , 

Your project is complete!
Congratulations! 🎉🎉 

To highlight:

- Congratulations on deploying your project
- Congratulations on adding the video
- Congratulations on adding the Acknowledgements to the design's author

Now there is nothing left to do but to merge it! 🏆 

![](https://media2.giphy.com/media/l3fQc3aCV0HqpzWcU/giphy.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 21:33 UTC, merged